version: '3.8'

services:
###> doctrine/doctrine-bundle ###
  mariadb:
    image: mariadb:10.6.5
    container_name: '${APP_NAME}-mariadb'
    restart: on-failure
    volumes:
      - ./docker/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=database
      - MYSQL_USER=root
    ports:
      - "3306:3306"
###< doctrine/doctrine-bundle ###

  web:
    image: nginx:1.19.10
    container_name: '${APP_NAME}-web'
    working_dir: /application
    depends_on:
      - php
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  php:
    build: docker/php-fpm
    container_name: '${APP_NAME}-php'
    working_dir: /application
    volumes:
      - .:/application

  node:
    build: docker/node
    user: 'node'
    environment:
      - NODE_ENV=dev
    container_name: '${APP_NAME}-node'
    working_dir: /application
    expose:
      - "8081"
    command: yarn run watch
    volumes:
      - .:/application

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    container_name: '${APP_NAME}-mailer'
    ports: ["1025", "1080"]
###< symfony/mailer ###

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
