version: '3'

services:
###> doctrine/doctrine-bundle ###
  mariadb:
    image: mariadb:10.6.5
    container_name: '${APP_NAME}-mariadb'
    restart: on-failure
    volumes:
      - ./docker/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=database
      - MYSQL_USER=root
    ports:
      - "3003:3306"
###< doctrine/doctrine-bundle ###

  web:
    image: nginx:1.19.10
    container_name: '${APP_NAME}-web'
    working_dir: /application
    depends_on:
      - php
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  php:
    build: docker/php-fpm
    container_name: '${APP_NAME}-php'
    working_dir: /application
    volumes:
      - .:/application

  node:
    image: node:14.18.2-alpine
    container_name: '${APP_NAME}-node'
    working_dir: /application
    volumes:
      - .:/application

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
